# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ lib, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];
  boot = {
    initrd = {
      availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
      kernelModules = [ "amdgpu" "rtw89_8851bu" ]; # "rtw89_usb" "rtw89_8851b" "rtw89_core"
    };
    kernelParams = [
      "quiet"
      "amd_iommu=off"
      "mitigations=off"
      "amdgpu.sg_display=0"
      "processor.ignore_ppc=1"
      "amdgpu.gttsize=14750"
      "ttm.pages_limit=3776000"
      "ttm.page_pool_size=3776000"
      "usbcore.autosuspend=-1"
    ];
  };

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/fc78be52-e65c-48ea-b380-27f2e2a16141";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd:3" "ssd" "space_cache=v2" "noatime" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/7336-BC97";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  hardware = {
    enableRedistributableFirmware = true;
    cpu.amd = {
      updateMicrocode = true;
    };
    usb-modeswitch.enable = true;
    bluetooth.enable = true;
  };
}
